### ISSUE TITLE
Opgave 6 forsat

### ISSUE THREAD

**Issue by caspersiig** [TAULO/C_SKARP_Opgaver#1]
Du har i din opgave 6 forsat et click event du har sat i din XAML men ikke bruger
`        private void ClickEvent(object sender, RoutedEventArgs e)
        {

        }`
Og lige neden under har du en switch case der kan optimeres med en IF og Else
`           switch (content)
            {
                case "Vest":
                    textBox.AppendText("vest");
                    textBox.AppendText(Environment.NewLine);
                    break;
                case "Nord":
                    textBox.AppendText("Nord");
                    textBox.AppendText(Environment.NewLine);
                    break;
                case "Øst":
                    textBox.AppendText("Øst");
                    textBox.AppendText(Environment.NewLine);
                    break;
                case "Syd":
                    textBox.AppendText("Syd");
                    textBox.AppendText(Environment.NewLine);
                    break;
            }`

Hvem bruger også switch i 2022?

**Comment by TAULO** [comment]
Fuxk dig der er en genial løsning

Steve Jobs har også stalket min GitHub og nu starter han winmac 2022


Den 21. mar. 2022 kl. 11.19 skrev Casper Siig ***@***.***>:

﻿

Du har i din opgave 6 forsat et click event du har sat i din XAML men ikke bruger
` private void ClickEvent(object sender, RoutedEventArgs e)
{

    }`


Og lige neden under har du en switch case der kan optimeres med en IF og Else
switch (content) { case "Vest": textBox.AppendText("vest"); textBox.AppendText(Environment.NewLine); break; case "Nord": textBox.AppendText("Nord"); textBox.AppendText(Environment.NewLine); break; case "Øst": textBox.AppendText("Øst"); textBox.AppendText(Environment.NewLine); break; case "Syd": textBox.AppendText("Syd"); textBox.AppendText(Environment.NewLine); break; }

Hvem bruger også switch i 2022?

**Comment by caspersiig** [comment]
undskyld mig hr men vare din mund.

Din løsning er lort.

Carpe Diem

oderint dum metuant
